version: "2"
services:
  test-helper_ai_small:
    container_name: ai-server
    build:
      context: /
      dockerfile: Dockerfile
    image: test-helper_ai_small:latest
    ports:
      - 5000:5000